image: ruby:3.2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  BUNDLE_PATH: vendor/bundle

cache:
  paths:
    - $BUNDLE_PATH

before_script:
  - bundle update debug
  - bundle install --full-index
  # - bundle check || bundle install --jobs=4
  - echo "end bundle install"
  - bundle exec rails db:create db:migrate
  - echo "end rails db:create db:migrate"
  - bundle exec rails db:create RAILS_ENV=test

stages:
  - generate_yard_doc
  - publish_yard_doc

generate_yard_doc:
  stage: generate_yard_doc
  script:
    - bundle exec yard
    - git add .
    - git commit -m "$(date "+%Y-%m-%d")"
    - git push

publish_yard_doc:
  stage: publish_yard_doc
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d doc
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
