image: ruby:3.2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  BUNDLE_PATH: vendor/bundle
  # Todo: 修正 https://gitlab.com/gitlab-org/gitlab/-/issues/292668
  USER_EMAIL: example.bot
  USER_NAME: bot@example.com

cache:
  paths:
    - $BUNDLE_PATH
    - $USER_EMAIL
    - $USER_NAME

before_script:
  - bundle update debug
  - bundle install --full-index
  - bundle exec rails db:create db:migrate
  - bundle exec rails db:create db:migrate RAILS_ENV=test

stages:
  - generate_yard_doc
  - publish_yard_doc

generate_yard_doc:
  stage: generate_yard_doc
  script:
    - bundle exec yard
    - git config --global user.email $USER_EMAIL
    - git config --global user.name $USER_NAME
    - git add .
    - git commit -m "$(date "+%Y-%m-%d")"
    - git push

publish_yard_doc:
  stage: publish_yard_doc
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d doc
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
