image: ruby:3.2

yard_doc:
  # tags:
  #   - yard_doc
  stage: build
  rules:
    - when: manual
  variables:
    USER_EMAIL: yarddoc_test # https://gitlab.com/gitlab-org/gitlab/-/issues/292668
    USER_NAME: yarddoc_test@noreply.gitlab.com
    GITLAB_TOKEN: $PERSONAL_ACCESS_TOKENS # Settings > CI/CD > Variables
    GITLAB_REPOSITORY: https://gitlab.com/husita-h/practice_yard_doc
    OUTPUT_DIR: yarddocs
  cache:
    paths:
      - vendor/bundle/
  before_script:
    - apt update
    - apt install git -y
    - mkdir -p $OUTPUT_DIR && mkdir -p $OUTPUT_DIR/pulic
    - bundle config set --local path 'vendor/bundle'
    - bundle update debug
    - bundle add yard
    - bundle install
    - git clone "https//oauth2:"$GITLAB_TOKEN"@$GITLAB_TOKEN" $OUTPUT_DIR --depth 1
  script:
    - bundle exec yard -o $OUTPUT_DIR/public
    - cd $OUTPUT_DIR
    - >
      if [`git status -z | wc -c` -gt 0] then;
        git config --global user.email $USER_NAME
        git config --global user.name $USER_EMAIL
        git add .
        git commit -m "update yard doc"`date +%Y%m%d%H%M%S`
        git push origin main
      else
        echo "not changed"
      fi
    - rm -rf $OUTPUT_DIR
